<?php
_("Delete Project");
_("Are you sure you want to remove");
_("from the system?");
_("Cancel");
_("Delete");
_("Edit");
_("Add Position");
_('Position Information');
_('Title');
_('Position Type :');
_('Hourly Pay Rate');
_('Target Number of Volunteers');
_('Description');
_('Submit');
_('Cancel');
_('Modify Task');
_('Task');
_('Update');
_("Name");
_("Description");
_("no projects");
_("Edit");
_("Delete");
_("Assign Volunteers");
_("Refresh");
_("Project Name :");
_("Start Date :");
_("End Date :");
_("Location :");
_("Volunteers assigned :");
_("Positions");
_("# Volunteers");
_("Title");
_("Description");
_("Pay Rate");
_("Target");
_("Assigned");
_("Actions");
_("edit");
_("remove");
_("Add a position");
_("Positions");
_("There are no positions assigned to");
_("Add a position");
_("Description");
_("Specialties needed");
_("Volunteers working on");
_("No volunteers are currently assigned to");
_("Project");
_('Project Information');
_('Name');
_('Start date :');
_('End date :');
_('Description');
_('Base Location');
_('Submit');
_('Cancel');
_("Assign Volunteers");
_("You are currently not assigned as a site manager to any projects.");
_("First please select a project to assign to:");
_('Project to assign to');
_('Continue');
_("Date:");
_("Time:");
_("Date:");
_("Time:");
_("now");
_("or # hours:");
_("Delete Volunteer");
_("Are you sure you want to retire");
_("Cancel");
_("Delete");
_("Volunteers to Assign");
_("Name");
_("Picture");
_("Status");
_("Affiliation");
_("Project - Position");
_("Availability");
_("Start");
_("Availability");
_("End");
_("Hours");
_("Identification");
_("Location");
_("Specialties");
_("Assign");
_("Remove From Project");
_("Assigned");
_("Unassigned");
_("Position:");
_("Assign this Volunteer");
_('To assign another volunteer, you must perform another search because no other volunteers match the current search criteria');
_('No volunteers were found. Please refine your criteria and try again');
_('Alternatively, you can try the');
_('specifying \'Loose Name Matching\'');
_("Edit");
_("Delete");
_("Name:");
_("Gender:");
_("Date of Birth:");
_("Contact Info");
_("Availability");
_("Work Begin:");
_("Work End:");
_("Work Hour Begin:");
_("Work Hour End:");
_("Work Details");
_("Occupation:");
_("Affiliation:");
_("Project");
_("Position");
_("Log Time");
_("Log time");
_("Skills and Work Restrictions");
_("Special Needs:");
_("Approve Site Managers");
_("Current or Previous Applicants");
_("There are no managers to approve or revoke manager approval from.");
_("Current Status");
_("Approve");
_("Deny / Revoke");
_("Volunteer");
_("Approved");
_("Denied");
_("Unapproved");
_('Revoke');
_('Deny');
_("Upgrade Non-Applicants");
_("Upgrade this Volunteer to Site Manager Status");
_("Volunteer Management");
_("The Volunteer Management module keeps track of projects and volunteers.");
_("Volunteer Portal");
_("My information page");
_("Personal information and time logging.");
_("Assign to Project");
_("Manage volunteer assignments");
_("Show Assigned");
_("View all volunteers assigned to projects");
_("View All Volunteers");
_("View all registered volunteers");
_("Search");
_("Search for a volunteer");
_("Add New Project");
_("Start a new project");
_("View My Projects");
_("View all projects you are currently assigned to");
_("View All Projects");
_("View all projects being tracked");
_("Generate report");
_("Generate customized report on volunteers and projects");
_("Register to VM");
_("Register yourself in Volunteer Management module");
_("Send messages");
_("Send messages to other users");
_("Current projects");
_("You are not assigned to any project.");
_("Click here");
_("to view your projects");
_("Current features include:");
_("Manage volunteer assignment");
_("Start and view projects");
_("Search volunteers");
_("Send and receive messages");
_("Version");
_("Last Modified");
_("Volunteer Registry - Thank you for your help!");
_("To register, fill in as many of the below fields as possible. When you are finished, click \"Submit\". Your registration will be confirmed via phone or email.");
_("Edit details");
_('Personal Details');
_('Name in Full :');
_('Date of Birth :');
_('Male');
_('Female');
_('Gender :');
_('Type of Identification :');
_('Identification Number :');
_('Create a Sahana account');
_("Remember this information, because you will use it to log into Sahana.");
_('Username :');
_('Password :');
_('Re-Type Password :');
_('Work Details');
_('Affiliation :');
_('Organizations are populated through the Organization Registry module. Contact an administrator if you do not see your organization.');
_('Occupation :');
_('Skills');
_('Please select your skills and limitations below.');
_('NOTE: Selecting a category will select all options below it.');
_('When you select a checkbox that has a ');
_(' next to it, you are selecting all options that fall under that category. For this reason, make sure that you review the options you select by expanding until you see a ');
_('Optionally, you may enter any special needs. Please use commas to separate multiple needs:');
_('Special needs:');
_('Availability');
_('Start Date :');
_('End Date :');
_('Base Location');
_('Contact Information');
_('Picture');
_('Optionally, you may upload a picture to identify yourself.');
_('Image file:');
_('Current picture');
_("Please enter at least one field below:");
_('Personal Information');
_('Any ID Number:');
_('Name:');
_('Loose Name Matching');
_('Skills');
_('Require ALL skills below');
_('Require ANY skills below');
_('Skills Matching:');
_('Search');
_("Advanced Search Criteria");
_("Back to Basic Search");
_("Basic Search Criteria");
_("Advanced Search");
_("Search results are returned only if they match ALL selected fields.");
_("Please enter at least one field below:");
_("Filter volunteer results by any one of the following fields:");
_('Personal Information');
_('Any ID Number:');
_('Name:');
_('advanced');
_('Options');
_('Loose Name Matching');
_('Find similar sounding names');
_('Show only unassigned');
_('Location');
_('Skills');
_('Require ALL skills below');
_('Require ANY skills below');
_('and_skills');
_('Availability');
_('Volunteer must be available for the ENTIRE time specified below');
_('Volunteer must be available for ANY PORTION of the time specified below');
_('Start date :');
_('End date :');
_("Page");
_("Go to Previous Page");
_("Previous");
_("Go to First Page");
_("1");
_('Go to Page No ');
_('Go to Last Page');
_('Go to Next Page');
_('Next');
_("Records per page");
_("Update");
_("hours for review on");
_("Name");
_("Project");
_("Position");
_("Pay Rate ");
_("Start ");
_("End ");
_("Approved:");
_("Denied:");
_("Report on My Projects");
_('Create Report');
_("Create Custom Report");
_('Filter by Project, Organization, or Both');
_('By Project:');
_('By Organization:');
_('Create Project or Organization Report');
_('Report by Specific Volunteers');
_('To add a volunteer to the list, select one in the \'List of Volunteers\' below and click on \'Add\'.');
_('To remove a volunteer from the list, click on the remove link next to his name.');
_('List of Volunteers :');
_('Create Custom Report for these Volunteers');
_('You must select at least one volunteer if reporting by volunteer.');
_('Change Password');
_('Current Password :');
_('New Password :');
_('Re-Type New Password :');
_('Change Password');
_("Pending Hours Approval");
_("Name :");
_("Project :");
_("View Hours");
_("Skills Modifications");
_('Add a new skill');
_('Skill Description :');
_('Code [4-5 letter unique abbreviation] : ');
_('Add');
_("No skills defined.");
_('Remove');
_("In order to begin, please log in using the Sahana account you just created.");
_("View Printer Friendly Version");
_("View Printer Friendly Version");
_("Viewing Report For");
_("Specific Volunteers");
_("All Volunteers Part of Organization:");
_("Restricting Results by Project:");
_("Project:");
_("Organization:");
_("All Volunteers that Ever Worked on any Projects");
_("Name");
_("Status");
_("Affiliation");
_("Total Positions Held");
_("Total Hours");
_("Total Monetary Value");
_("Details");
_("Active");
_("Retired");
_('Position:');
_('Position Status:');
_('Hours:');
_('Hourly Rate:');
_('Monetary Value:');
_('Project:');
_('no positions held');
_('Status');
_('Active');
_('Retired');
_('Affiliation');
_('Positions');
_('Total Hours');
_('Total Payment');
_("none");
_("Total Hours");
_("Total Monetary Value");
_("Administrative Functions");
_("The following is a description of each administrative function for the VM module");
_("Access Control Modifications");
_("Modify how access to the VM module is handled");
_("Update Search Registry");
_("Since a volunteer's name may change in other places in Sahana, you may have to periodically update the search registry with current sounds-like name matching for volunteer searching");
_("Clear Template Cache");
_("Delete all PHP templates that have been cached");
_("Audit ACL");
_("Verify that all 'act' and 'vm_action' combinations in the VM code are under access control and that all VM tables/views are classified");
_("Access Control");
_("Please select a situation below to modify access to:");
_("Continue");
_("Access Control");
_("Table Name");
_("Create");
_("Read");
_("Update");
_("Delete");
_("Remove From List");
_("Special Constraints");
_("on");
_("Save Changes");
_("Cancel Changes");
_("VM Admin Home");
_("Access Control Modifications");
_("Update Search Registry");
_("Clear Template Cache");
_("Audit ACL");
_("ACL Audit");
_("All access requests in the database and in the VM code match.");
_("Warning:");
_("The following requests in the VM code are not under access control:");
_("Description");
_("Add");
_("Add");
_("Please enter a description");
_("Warning");
_("The following requests in the database are never referenced");
_("Description");
_("Remove From Database");
_("Remove");
_("Warning");
_("The following database tables/views have not been given any classification level");
_("Table");
_("Classification Level");
_("Add");
_("Add");
_("Inbox");
_("Outbox");
_("Delete");
_("From");
_("To");
_("Date Sent");
_("Preview");
_("Are you sure you want to delete this message?");
_("Your");
_("is empty");
_('Message not found.');
_("Back to Inbox");
_("Back to Outbox");
_("Are you sure you want to delete this message?");
_("Delete this message");
_('To');
_('To List:');
_('To add a volunteer to the \'To\' list, select one in the \'List of Volunteers\' below and click on \'Add\'. To remove a volunteer from the \'To\' list, click on the remove link next to his name.');
_('List of Volunteers :');
_('Add');
_('Message');
_('Message :');
_('Send');
