<li><a href="index.php?mod=admin&act=ims_config"><?php echo _("Configuration"); ?></a></li>
<li><a href="index.php?mod=admin&act=ims_level1"><?php echo _("Manage ") . _lc($conf['mod_admin_ims_level1']); ?></a></li>
<li><a href="index.php?mod=admin&act=ims_level2"><?php echo _("Manage ") . _lc($conf['mod_admin_ims_level2']); ?></a></li>
<li><a href="index.php?mod=admin&act=ims_level3"><?php echo _("Manage ") . _lc($conf['mod_admin_ims_level3']); ?></a></li>
